"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import wx
import mainframe

# Implementing MainFrame
class PiDebugMainFrame( mainframe.MainFrame ):
	def __init__( self, parent ):
		mainframe.MainFrame.__init__( self, parent )

	# Handlers for MainFrame events.
	def run_control( self, event ):
		# TODO: Implement run_control
		pass


